version: "3"
services:
  flaskapp:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      USE_POSTGRES: peutimporte 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
